export const SET_USER_DATA = "SET_USER_DATA";
export const NOT_LOADING = "NOT_LOADING";
export const START_LOADING = "START_LOADING";
export const GET_PRODUCT = "GET_PRODUCT";
export const EMPTY_MEASUREMENT = "EMPTY_MEASUREMENT";
export const GET_ORDER = "GET_ORDER";
export const PRODUCT_DISCRIPTIONS = "PRODUCT_DISCRIPTIONS";
